// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode() {
  return window['go']['app']['App']['AddNode']();
}

export function DeleteNode() {
  return window['go']['app']['App']['DeleteNode']();
}

export function GetNodes() {
  return window['go']['app']['App']['GetNodes']();
}
