// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddNode():Promise<Array<model.Node>>;

export function DeleteNode():Promise<Array<model.Node>>;

export function GetNodes():Promise<Array<model.Node>>;
